sonar.projectKey=romainsessa_visiplus-plan-tests
sonar.organization=romainsessa-1
sonar.sources=book/src/main,book-front/src
sonar.tests=book/src/test
sonar.exclusions=**/*.spec.ts, **/node_modules/**
sonar.test.inclusions=**/*.spec.ts

sonar.java.binaries=book/target/classes
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=book-front/coverage/lcov.info
sonar.coverage.jacoco.xmlReportPaths=book/target/site/jacoco/jacoco.xml
