name: Full CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Run backend tests
        run: mvn clean test --file book/pom.xml

  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: npm
          cache-dependency-path: book-front/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: book-front

      - name: Run unit tests (Jest)
        run: npm run test
        working-directory: book-front

  e2e:
    runs-on: ubuntu-latest
    needs: [backend, frontend]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Start backend
        run: |
          mvn spring-boot:run --file book/pom.xml &
          sleep 15

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install frontend
        run: npm install
        working-directory: book-front

      - name: Start frontend
        run: |
          npm run start &
          sleep 10
        working-directory: book-front

      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          working-directory: book-front
          start: echo "already started"

  sonar:
    runs-on: ubuntu-latest
    needs: [backend, frontend]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'  
      - name: Build backend
        run: mvn clean package --file book/pom.xml
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Install frontend dependencies
        run: npm install
        working-directory: book-front
      - name: Run unit tests (Jest)
        run: npm run test
        working-directory: book-front
      # Analyse SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
