name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean test --file book/pom.xml
      
  frontend-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: npm
        cache-dependency-path: book-front/package-lock.json
    - name: Install
      run: npm install
      working-directory: book-front
    - name: Run tests
      run: npm run test
      working-directory: book-front
